from __future__ import annotations

from typing import Any


class DeterministicResponseBuilder:
    """
    Build final user-facing answers directly from verified tool results.

    Ollama is not required for:
    - financial calculations
    - company comparisons

    This prevents the model from:
    - changing verified values
    - producing unrelated summaries
    - recalculating results
    - introducing unsupported information
    """

    def build_answer(
        self,
        selected_tool: str,
        calculation: dict[str, Any] | None = None,
        comparison: dict[str, Any] | None = None,
    ) -> str | None:
        """
        Return a deterministic answer when the selected tool supports it.

        Returns None when the answer should still be generated by the LLM.
        """

        if selected_tool == "financial_calculator":
            return self.build_calculation_answer(
                calculation
            )

        if selected_tool == "company_comparison":
            return self.build_comparison_answer(
                comparison
            )

        return None

    def build_calculation_answer(
        self,
        calculation: dict[str, Any] | None,
    ) -> str:
        """
        Build a clean answer from a verified financial calculation.
        """

        if not calculation:
            return (
                "The financial calculation could not be completed "
                "because no verified calculation result was available."
            )

        if not calculation.get("success"):
            error = calculation.get(
                "error",
                "The required financial values were unavailable.",
            )

            return (
                "The financial calculation could not be completed.\n\n"
                f"Reason: {error}"
            )

        results = calculation.get(
            "results",
            [],
        )

        if not results:
            return (
                "The financial calculation completed without a usable "
                "verified result."
            )

        answer_sections: list[str] = []

        for result in results:
            answer_sections.append(
                self._format_calculation_result(
                    result
                )
            )

        return "\n\n".join(answer_sections)

    def _format_calculation_result(
        self,
        result: dict[str, Any],
    ) -> str:
        """
        Format one company's verified calculation.
        """

        company = result.get(
            "company",
            "The company",
        )

        metric = result.get(
            "metric",
            "financial metric",
        )

        current_year = result.get(
            "current_year",
            "current period",
        )

        previous_year = result.get(
            "previous_year",
            "previous period",
        )

        current_value = result.get(
            "current_value",
        )

        previous_value = result.get(
            "previous_value",
        )

        verified_result = result.get(
            "result",
        )

        unit = result.get(
            "unit",
            "percent",
        )

        formula = result.get(
            "formula",
            (
                "((Current Value - Previous Value) / "
                "Previous Value) × 100"
            ),
        )

        metric_title = self._format_metric_name(
            metric
        )

        current_display = self._format_number(
            current_value
        )

        previous_display = self._format_number(
            previous_value
        )

        result_display = self._format_number(
            verified_result
        )

        interpretation = (
            self._build_growth_interpretation(
                company=company,
                metric_title=metric_title,
                result=verified_result,
                current_year=current_year,
            )
        )

        result_suffix = (
            "%"
            if unit == "percent"
            else f" {unit}"
        )

        return (
            f"## {metric_title} Growth\n\n"
            f"{company}'s {metric_title.lower()} changed from "
            f"**{previous_display} in {previous_year}** to "
            f"**{current_display} in {current_year}**.\n\n"
            f"**Formula**\n\n"
            f"{formula}\n\n"
            f"**Verified result: "
            f"{result_display}{result_suffix}**\n\n"
            f"**Interpretation**\n\n"
            f"{interpretation}"
        )

    def build_comparison_answer(
        self,
        comparison: dict[str, Any] | None,
    ) -> str:
        """
        Build a clean answer from a verified company comparison.
        """

        if not comparison:
            return (
                "The company comparison could not be completed "
                "because no verified comparison result was available."
            )

        if not comparison.get("success"):
            error = comparison.get(
                "error",
                "The required company values were unavailable.",
            )

            return (
                "The company comparison could not be completed.\n\n"
                f"Reason: {error}"
            )

        results = comparison.get(
            "results",
            [],
        )

        if len(results) < 2:
            return (
                "The comparison requires verified values for at least "
                "two companies."
            )

        metric = comparison.get(
            "metric",
            "financial metric",
        )

        metric_title = self._format_metric_name(
            metric
        )

        value_lines: list[str] = []

        years = set()

        for result in results:
            company = result.get(
                "company",
                "Unknown company",
            )

            year = result.get(
                "year",
                "Unknown year",
            )

            value = self._format_number(
                result.get("value")
            )

            years.add(
                str(year)
            )

            value_lines.append(
                f"- **{company}:** {value} "
                f"(fiscal year {year})"
            )

        highest_company = comparison.get(
            "highest_company",
            "Unknown company",
        )

        highest_value = self._format_number(
            comparison.get(
                "highest_value"
            )
        )

        lowest_company = comparison.get(
            "lowest_company",
            "Unknown company",
        )

        lowest_value = self._format_number(
            comparison.get(
                "lowest_value"
            )
        )

        absolute_difference = self._format_number(
            comparison.get(
                "absolute_difference"
            )
        )

        percentage_difference = comparison.get(
            "percentage_difference"
        )

        answer_parts = [
            f"## {metric_title} Comparison",
            "",
            *value_lines,
            "",
            f"**Higher value:** {highest_company} "
            f"with {highest_value}",
            "",
            f"**Lower value:** {lowest_company} "
            f"with {lowest_value}",
            "",
            f"**Absolute difference:** {absolute_difference}",
        ]

        if percentage_difference is not None:
            answer_parts.extend(
                [
                    "",
                    (
                        "**Percentage difference:** "
                        f"{self._format_number(percentage_difference)}%"
                    ),
                ]
            )

        answer_parts.extend(
            [
                "",
                "**Conclusion**",
                "",
                (
                    f"{highest_company} reported the higher "
                    f"{metric_title.lower()} value."
                ),
            ]
        )

        if len(years) > 1:
            answer_parts.extend(
                [
                    "",
                    (
                        "The companies use different reporting periods, "
                        "so the comparison should be interpreted with "
                        "that limitation."
                    ),
                ]
            )

        return "\n".join(answer_parts)

    @staticmethod
    def _build_growth_interpretation(
        company: str,
        metric_title: str,
        result: Any,
        current_year: Any,
    ) -> str:
        """
        Create a short interpretation from the verified growth value.
        """

        if not isinstance(
            result,
            (int, float),
        ):
            return (
                f"The verified result describes the change in "
                f"{company}'s {metric_title.lower()} for {current_year}."
            )

        if result > 0:
            direction = "increased"
        elif result < 0:
            direction = "decreased"
        else:
            direction = "remained unchanged"

        if result == 0:
            return (
                f"{company}'s {metric_title.lower()} remained unchanged "
                f"in {current_year} compared with the previous period."
            )

        magnitude = abs(
            result
        )

        if magnitude < 3:
            strength = "modestly"
        elif magnitude < 10:
            strength = "moderately"
        else:
            strength = "significantly"

        return (
            f"{company}'s {metric_title.lower()} {direction} "
            f"{strength} in {current_year} compared with the "
            "previous period."
        )

    @staticmethod
    def _format_metric_name(
        metric: Any,
    ) -> str:
        """
        Convert internal metric names into readable labels.
        """

        if not isinstance(metric, str):
            return "Financial Metric"

        metric_names = {
            "revenue": "Revenue",
            "net_income": "Net Income",
            "operating_income": "Operating Income",
            "eps": "EPS",
            "cash_flow": "Cash Flow",
            "free_cash_flow": "Free Cash Flow",
            "gross_margin": "Gross Margin",
            "operating_margin": "Operating Margin",
            "net_profit_margin": "Net Profit Margin",
            "current_ratio": "Current Ratio",
        }

        return metric_names.get(
            metric,
            metric.replace(
                "_",
                " ",
            ).title(),
        )

    @staticmethod
    def _format_number(
        value: Any,
    ) -> str:
        """
        Format numeric values without changing their meaning.
        """

        if value is None:
            return "Unavailable"

        if isinstance(
            value,
            bool,
        ):
            return str(value)

        if isinstance(
            value,
            int,
        ):
            return f"{value:,}"

        if isinstance(
            value,
            float,
        ):
            if value.is_integer():
                return f"{int(value):,}"

            return f"{value:,.2f}"

        return str(value)


if __name__ == "__main__":
    builder = DeterministicResponseBuilder()

    calculation_test = {
        "success": True,
        "calculation_type": "growth_rate",
        "metric": "revenue",
        "results": [
            {
                "company": "Apple",
                "metric": "revenue",
                "current_year": 2024,
                "current_value": 391035.0,
                "previous_year": 2023,
                "previous_value": 383285.0,
                "result": 2.02,
                "unit": "percent",
                "formula": (
                    "((Current Value - Previous Value) / "
                    "Previous Value) × 100"
                ),
            }
        ],
        "error": None,
    }

    comparison_test = {
        "success": True,
        "tool": "company_comparison",
        "metric": "revenue",
        "results": [
            {
                "company": "Apple",
                "metric": "revenue",
                "year": 2024,
                "value": 391035.0,
            },
            {
                "company": "Microsoft",
                "metric": "revenue",
                "year": 2024,
                "value": 245122.0,
            },
        ],
        "highest_company": "Apple",
        "highest_value": 391035.0,
        "lowest_company": "Microsoft",
        "lowest_value": 245122.0,
        "absolute_difference": 145913.0,
        "percentage_difference": 59.53,
        "error": None,
    }

    print("=" * 80)
    print("CALCULATION ANSWER\n")

    print(
        builder.build_answer(
            selected_tool="financial_calculator",
            calculation=calculation_test,
        )
    )

    print("\n" + "=" * 80)
    print("COMPARISON ANSWER\n")

    print(
        builder.build_answer(
            selected_tool="company_comparison",
            comparison=comparison_test,
        )
    )