from __future__ import annotations

from typing import Any

from backend.app.services.financial_response_formatter import (
    FinancialResponseFormatter,
)


class DeterministicResponseBuilder:
    """
    Build final user-facing answers directly from verified tool results.

    Ollama is not required for:
    - financial calculations
    - company comparisons
    - calculated comparisons

    This prevents the model from:
    - changing verified values
    - producing unrelated summaries
    - recalculating results
    - introducing unsupported information
    """

    def __init__(
        self,
        formatter: FinancialResponseFormatter | None = None,
    ) -> None:
        """
        Initialize the builder with a reusable response formatter.
        """

        self.formatter = (
            formatter
            if formatter is not None
            else FinancialResponseFormatter()
        )

    def build_answer(
        self,
        selected_tool: str,
        calculation: dict[str, Any] | None = None,
        comparison: dict[str, Any] | None = None,
        reasoning: dict[str, Any] | None = None,
    ) -> str | None:
        """
        Return a deterministic answer when the selected tool supports it.

        Returns None when the answer should still be generated by the LLM.
        """

        normalized_tool = (
            selected_tool.strip()
            if isinstance(selected_tool, str)
            else ""
        )

        if normalized_tool == "financial_calculator":
            return self.build_calculation_answer(
                calculation
            )

        if normalized_tool == "company_comparison":
            return self.build_comparison_answer(
                comparison
            )

        if normalized_tool == "calculated_comparison":
            return self.build_calculated_comparison_answer(
                reasoning
            )

        return None

    def build_calculation_answer(
        self,
        calculation: dict[str, Any] | None,
    ) -> str:
        """
        Build a formatted answer from a verified financial calculation.
        """

        if not isinstance(
            calculation,
            dict,
        ):
            return self.formatter.format_error(
                title="Financial Calculation",
                reason=(
                    "No verified calculation result was available."
                ),
            )

        if not calculation.get(
            "success",
            False,
        ):
            error = calculation.get(
                "error",
                "The required financial values were unavailable.",
            )

            return self.formatter.format_error(
                title="Financial Calculation",
                reason=str(error),
            )

        results = calculation.get(
            "results",
            [],
        )

        if not isinstance(
            results,
            list,
        ) or not results:
            return self.formatter.format_error(
                title="Financial Calculation",
                reason=(
                    "The calculation completed without a usable "
                    "verified result."
                ),
            )

        answer_sections: list[str] = []

        for result in results:
            if not isinstance(
                result,
                dict,
            ):
                continue

            answer_sections.append(
                self._format_calculation_result(
                    result
                )
            )

        if not answer_sections:
            return self.formatter.format_error(
                title="Financial Calculation",
                reason=(
                    "The calculation results did not contain "
                    "valid company data."
                ),
            )

        return "\n\n---\n\n".join(
            answer_sections
        )

    def _format_calculation_result(
        self,
        result: dict[str, Any],
    ) -> str:
        """
        Prepare one company's verified calculation for formatting.
        """

        company = result.get(
            "company",
            "The company",
        )

        metric = result.get(
            "metric",
            "financial metric",
        )

        current_year = result.get(
            "current_year",
            "Current period",
        )

        previous_year = result.get(
            "previous_year",
            "Previous period",
        )

        current_value = result.get(
            "current_value",
        )

        previous_value = result.get(
            "previous_value",
        )

        verified_result = result.get(
            "result",
        )

        unit = result.get(
            "unit",
            "percent",
        )

        formula = result.get(
            "formula",
            (
                "((Current Value - Previous Value) / "
                "Previous Value) × 100"
            ),
        )

        metric_title = self._format_metric_name(
            metric
        )

        interpretation = self._build_growth_interpretation(
            company=str(company),
            metric_title=metric_title,
            result=verified_result,
            current_year=current_year,
        )

        result_suffix = self._build_result_suffix(
            unit
        )

        return self.formatter.format_calculation_result(
            company=str(company),
            metric_title=metric_title,
            previous_year=previous_year,
            previous_value=previous_value,
            current_year=current_year,
            current_value=current_value,
            formula=str(formula),
            result_value=verified_result,
            result_suffix=result_suffix,
            interpretation=interpretation,
        )

    def build_comparison_answer(
        self,
        comparison: dict[str, Any] | None,
    ) -> str:
        """
        Build a formatted answer from a verified company comparison.
        """

        if not isinstance(
            comparison,
            dict,
        ):
            return self.formatter.format_error(
                title="Company Comparison",
                reason=(
                    "No verified comparison result was available."
                ),
            )

        if not comparison.get(
            "success",
            False,
        ):
            error = comparison.get(
                "error",
                "The required company values were unavailable.",
            )

            return self.formatter.format_error(
                title="Company Comparison",
                reason=str(error),
            )

        results = comparison.get(
            "results",
            [],
        )

        if not isinstance(
            results,
            list,
        ) or len(results) < 2:
            return self.formatter.format_error(
                title="Company Comparison",
                reason=(
                    "Verified values for at least two companies "
                    "are required."
                ),
            )

        valid_results = [
            result
            for result in results
            if isinstance(
                result,
                dict,
            )
        ]

        if len(valid_results) < 2:
            return self.formatter.format_error(
                title="Company Comparison",
                reason=(
                    "The comparison results did not contain "
                    "valid data for at least two companies."
                ),
            )

        metric = comparison.get(
            "metric",
            "financial metric",
        )

        metric_title = self._format_metric_name(
            metric
        )

        years = {
            str(
                result.get(
                    "year",
                    "Unknown year",
                )
            )
            for result in valid_results
        }

        highest_company = comparison.get(
            "highest_company",
            "Unknown company",
        )

        highest_value = comparison.get(
            "highest_value",
        )

        lowest_company = comparison.get(
            "lowest_company",
            "Unknown company",
        )

        lowest_value = comparison.get(
            "lowest_value",
        )

        absolute_difference = comparison.get(
            "absolute_difference",
        )

        percentage_difference = comparison.get(
            "percentage_difference",
        )

        return self.formatter.format_comparison_result(
            metric_title=metric_title,
            results=valid_results,
            highest_company=str(highest_company),
            highest_value=highest_value,
            lowest_company=str(lowest_company),
            lowest_value=lowest_value,
            absolute_difference=absolute_difference,
            percentage_difference=percentage_difference,
            reporting_period_warning=len(years) > 1,
        )

    def build_calculated_comparison_answer(
        self,
        reasoning: dict[str, Any] | None,
    ) -> str:
        """
        Build a deterministic answer from verified calculated comparison
        reasoning.
        """

        if not isinstance(
            reasoning,
            dict,
        ):
            return self.formatter.format_error(
                title="Calculated Comparison",
                reason=(
                    "No verified calculated comparison result "
                    "was available."
                ),
            )

        if not reasoning.get(
            "success",
            False,
        ):
            error = reasoning.get(
                "error",
                (
                    "The calculated comparison could not "
                    "be completed."
                ),
            )

            return self.formatter.format_error(
                title="Calculated Comparison",
                reason=str(error),
            )

        ranked_results = reasoning.get(
            "ranked_results",
            [],
        )

        if not isinstance(
            ranked_results,
            list,
        ) or len(ranked_results) < 2:
            return self.formatter.format_error(
                title="Calculated Comparison",
                reason=(
                    "Verified calculations for at least two "
                    "companies are required."
                ),
            )

        valid_results = [
            result
            for result in ranked_results
            if isinstance(
                result,
                dict,
            )
        ]

        if len(valid_results) < 2:
            return self.formatter.format_error(
                title="Calculated Comparison",
                reason=(
                    "The reasoning result did not contain valid "
                    "data for at least two companies."
                ),
            )

        metric = reasoning.get(
            "metric",
            "financial metric",
        )

        metric_title = self._format_metric_name(
            metric
        )

        comparison_type = reasoning.get(
            "comparison_type",
            "calculated metric",
        )

        comparison_title = self._format_comparison_type(
            comparison_type
        )

        strongest_company = reasoning.get(
            "strongest_company",
            "Unknown company",
        )

        strongest_result = reasoning.get(
            "strongest_result",
        )

        weakest_company = reasoning.get(
            "weakest_company",
            "Unknown company",
        )

        weakest_result = reasoning.get(
            "weakest_result",
        )

        difference = reasoning.get(
            "difference_percentage_points",
        )

        conclusion = reasoning.get(
            "conclusion",
            "",
        )

        answer_parts = [
            (
                f"## {metric_title} "
                f"{comparison_title} Comparison"
            ),
            "",
            (
                "| Rank | Company | Previous Period | "
                "Current Period | Calculated Result |"
            ),
            "|---:|---|---:|---:|---:|",
        ]

        for index, result in enumerate(
            valid_results,
            start=1,
        ):
            company = result.get(
                "company",
                "Unknown company",
            )

            previous_year = result.get(
                "previous_year",
                "Previous period",
            )

            current_year = result.get(
                "current_year",
                "Current period",
            )

            calculated_result = result.get(
                "result",
            )

            unit = result.get(
                "unit",
                "percent",
            )

            result_suffix = self._build_result_suffix(
                unit
            )

            answer_parts.append(
                (
                    f"| {index} | {company} | "
                    f"{previous_year} | {current_year} | "
                    f"{self.formatter.format_number(calculated_result)}"
                    f"{result_suffix} |"
                )
            )

        answer_parts.extend(
            [
                "",
                "### Performance Summary",
                "",
                (
                    f"**Strongest performer:** "
                    f"{strongest_company} with "
                    f"{self.formatter.format_number(strongest_result)}%"
                ),
                "",
                (
                    f"**Weakest performer:** "
                    f"{weakest_company} with "
                    f"{self.formatter.format_number(weakest_result)}%"
                ),
            ]
        )

        if difference is not None:
            answer_parts.extend(
                [
                    "",
                    (
                        "**Difference:** "
                        f"{self.formatter.format_number(difference)} "
                        "percentage points"
                    ),
                ]
            )

        answer_parts.extend(
            [
                "",
                "### Conclusion",
                "",
                (
                    str(conclusion)
                    if conclusion
                    else (
                        f"{strongest_company} produced the strongest "
                        f"verified {metric_title.lower()} result."
                    )
                ),
            ]
        )

        return "\n".join(
            answer_parts
        )

    @staticmethod
    def _build_growth_interpretation(
        company: str,
        metric_title: str,
        result: Any,
        current_year: Any,
    ) -> str:
        """
        Create a short interpretation from the verified growth value.
        """

        if not isinstance(
            result,
            (int, float),
        ):
            return (
                f"The verified result describes the change in "
                f"{company}'s {metric_title.lower()} for "
                f"{current_year}."
            )

        if result > 0:
            direction = "increased"
        elif result < 0:
            direction = "decreased"
        else:
            direction = "remained unchanged"

        if result == 0:
            return (
                f"{company}'s {metric_title.lower()} remained "
                f"unchanged in {current_year} compared with the "
                "previous period."
            )

        magnitude = abs(
            result
        )

        if magnitude < 3:
            strength = "modestly"
        elif magnitude < 10:
            strength = "moderately"
        else:
            strength = "significantly"

        return (
            f"{company}'s {metric_title.lower()} {direction} "
            f"{strength} in {current_year} compared with the "
            "previous period."
        )

    @staticmethod
    def _build_result_suffix(
        unit: Any,
    ) -> str:
        """
        Build the display suffix for a verified calculation result.
        """

        if not isinstance(
            unit,
            str,
        ):
            return ""

        normalized_unit = unit.strip().lower()

        if normalized_unit in {
            "percent",
            "percentage",
            "%",
        }:
            return "%"

        if not normalized_unit:
            return ""

        return f" {unit.strip()}"

    @staticmethod
    def _format_comparison_type(
        comparison_type: Any,
    ) -> str:
        """
        Convert an internal calculation type into a readable title.
        """

        if not isinstance(
            comparison_type,
            str,
        ) or not comparison_type.strip():
            return "Calculated"

        comparison_names = {
            "growth_rate": "Growth",
            "percentage_change": "Percentage Change",
            "profit_margin": "Profit Margin",
            "gross_margin": "Gross Margin",
            "operating_margin": "Operating Margin",
            "net_profit_margin": "Net Profit Margin",
            "current_ratio": "Current Ratio",
            "debt_ratio": "Debt Ratio",
            "return_on_equity": "Return on Equity",
            "return_on_assets": "Return on Assets",
            "calculated_metric": "Calculated",
        }

        normalized_type = comparison_type.strip()

        return comparison_names.get(
            normalized_type,
            normalized_type.replace(
                "_",
                " ",
            ).title(),
        )

    @staticmethod
    def _format_metric_name(
        metric: Any,
    ) -> str:
        """
        Convert internal metric names into readable labels.
        """

        if not isinstance(
            metric,
            str,
        ):
            return "Financial Metric"

        metric_names = {
            "revenue": "Revenue",
            "net_income": "Net Income",
            "operating_income": "Operating Income",
            "eps": "EPS",
            "cash_flow": "Cash Flow",
            "free_cash_flow": "Free Cash Flow",
            "gross_margin": "Gross Margin",
            "operating_margin": "Operating Margin",
            "net_profit_margin": "Net Profit Margin",
            "current_ratio": "Current Ratio",
            "debt_ratio": "Debt Ratio",
            "return_on_equity": "Return on Equity",
            "roe": "Return on Equity",
            "return_on_assets": "Return on Assets",
            "roa": "Return on Assets",
        }

        normalized_metric = metric.strip()

        return metric_names.get(
            normalized_metric,
            normalized_metric.replace(
                "_",
                " ",
            ).title(),
        )


if __name__ == "__main__":
    builder = DeterministicResponseBuilder()

    calculation_test = {
        "success": True,
        "calculation_type": "growth_rate",
        "metric": "revenue",
        "results": [
            {
                "company": "Apple",
                "metric": "revenue",
                "current_year": 2024,
                "current_value": 391035.0,
                "previous_year": 2023,
                "previous_value": 383285.0,
                "result": 2.02,
                "unit": "percent",
                "formula": (
                    "((Current Value - Previous Value) / "
                    "Previous Value) × 100"
                ),
            }
        ],
        "error": None,
    }

    comparison_test = {
        "success": True,
        "tool": "company_comparison",
        "metric": "revenue",
        "results": [
            {
                "company": "Apple",
                "metric": "revenue",
                "year": 2024,
                "value": 391035.0,
            },
            {
                "company": "Microsoft",
                "metric": "revenue",
                "year": 2024,
                "value": 245122.0,
            },
        ],
        "highest_company": "Apple",
        "highest_value": 391035.0,
        "lowest_company": "Microsoft",
        "lowest_value": 245122.0,
        "absolute_difference": 145913.0,
        "percentage_difference": 59.53,
        "error": None,
    }

    reasoning_test = {
        "success": True,
        "reasoning_type": "calculated_comparison",
        "comparison_type": "growth_rate",
        "metric": "revenue",
        "ranked_results": [
            {
                "company": "Microsoft",
                "metric": "revenue",
                "current_year": 2024,
                "previous_year": 2023,
                "current_value": 245122.0,
                "previous_value": 211915.0,
                "result": 15.67,
                "unit": "percent",
            },
            {
                "company": "Apple",
                "metric": "revenue",
                "current_year": 2024,
                "previous_year": 2023,
                "current_value": 391035.0,
                "previous_value": 383285.0,
                "result": 2.02,
                "unit": "percent",
            },
        ],
        "strongest_company": "Microsoft",
        "strongest_result": 15.67,
        "weakest_company": "Apple",
        "weakest_result": 2.02,
        "difference_percentage_points": 13.65,
        "conclusion": (
            "Microsoft was the stronger performer based on "
            "revenue growth. Microsoft reported 15.67% growth "
            "compared with Apple's 2.02%, a difference of "
            "13.65 percentage points."
        ),
        "error": None,
    }

    print("=" * 80)
    print("CALCULATION ANSWER\n")

    print(
        builder.build_answer(
            selected_tool="financial_calculator",
            calculation=calculation_test,
        )
    )

    print("\n" + "=" * 80)
    print("COMPARISON ANSWER\n")

    print(
        builder.build_answer(
            selected_tool="company_comparison",
            comparison=comparison_test,
        )
    )

    print("\n" + "=" * 80)
    print("CALCULATED COMPARISON ANSWER\n")

    print(
        builder.build_answer(
            selected_tool="calculated_comparison",
            reasoning=reasoning_test,
        )
    )